version: '3'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
        container_name: elasticsearch
        ports: 
            - "9200:9200"
        environment:
            - xpack.security.enabled=false
        volumes:
            - "es_data:/usr/share/elasticsearch/data"
        
    kibana:
        image: docker.elastic.co/kibana/kibana:5.6.1
        container_name: kibana
        ports: 
            - "5601:5601"
        depends_on: 
            - "elasticsearch"
        restart: always
        
volumes:
     es_data:
